import { Parameter } from "../model/Service";

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'menu.overview': 'Overview',
    'menu.eventlist': 'Events',
    'menu.quickbooking': 'Quick booking',
    'menu.planv2': 'Plan',
    'menu.plan': 'Plan',
    'menu.setting': 'Settings',
    'menu.setting-language': 'Language',
    'menu.setting-language.Vi': 'Vietnamese',
    'menu.setting-language.En': 'English',
    'menu.setting-aboutUs': 'About us',
    'menu.account': 'Account',
    'menu.emotion': 'Emotion detection',
    'menu.plansaved': 'Plan history',
    'menu.logoff': 'Log out',
    'menu.cammode': 'Camera View',
    'menu.currVersion': 'Current Version',
    'menu.newslist': 'News',
    'menu.sharedApp': 'Shared App',
    'menu.FanPage': 'FanPage',
    
    //tab
    'tab.overview': 'Overview',
    'tab.mysaved': 'My saved',
    'tab.plan': 'Plan',
    'tab.map': 'Map',
    'tab.account': 'Account',

    //overview
    'overviewpage.title': 'Overview',
    'overview.search': 'Search',
    'overview.eat': 'Eat',
    'overview.stay': 'Stay',
    'overview.see': 'See',
    'overview.shopping': 'Shopping',
    'overview.quickbooking': 'Quick booking',
    'overview.hotline': 'Contact Us',
    'overview.complaints': 'Complaints',
    'overview.popular': 'Popular',
    'overview.promotion': 'Promotions',
    'overview.utilities': 'Utilities',
    'overview.exchangerate': 'Exchange Rate',
    'overview.event': 'Events',
    'overview.culture': 'Specialty',
    'overview.advice': 'Advice',
    'overview.move': 'Transport',
    'overview.weather': 'Weather',
    'overview.karaoke': 'Entertainments',
    'overview.titleContact': 'Contact Information',
    'overview.bodySupportInfo': 'Support Contact',
    'overview.bodyHotline': 'Hotline',
    'overview.bodyAddress': 'Address',
    'overview.bodyWebsite': 'Website',
    'overview.detailpromotion': 'Promotion detail',
    'overview.saleoff': 'Sale off up to',

    //advice
    'advice-list.title-1': 'Advices when comming to ' + Parameter.cityName_EN,
    'advice-list.title-2': 'Good creation of art',
    'advice-list.title-3': 'Video clips about '+ Parameter.cityName_EN,
    'advice-list.title-4': 'Intangible cultural heritages',
    'advice-list.tab-poem': 'Poems',
    'advice-list.tab-video': 'Video Clips',
    'advice-list.tab-historicalitem': 'Intangible cultural heritage',

    //booking hotel
    'bkhtdt.title': 'Booking detail',
    'bkhtdt.contact': 'Contact',
    'bkhtdt.customer_name': 'Customer name',
    'bkhtdt.phoneno': 'Phone number',
    'bkhtdt.email': 'Email',
    'bkhtdt.bkinfo': 'Booking Information',
    'bkhtdt.time': 'Time',
    'bkhtdt.place': 'Place',
    'bkhtdt.nocustomer': 'Number of customer',
    'bkhtdt.createtime': 'Created time',
    'bkhtdt.price': 'Price',
    'bkhtdt.serviceprice': 'Service price',
    'bkhtdt.total': 'Total',
    'bkhtdt.noroom': 'Number of room',

    //booking hotel
    'bkht.title': 'Booking hotel room',
    'bkht.bookinginfo': 'Booking information',
    'bkht.fromdate': 'Check-in date',
    'bkht.todate': 'Check-out date',
    'bkht.roomtype': 'Room Type',
    'bkht.roomformat': 'Room Format',
    'bkht.noroom': 'Number of room',
    'bkht.checkav': 'Check available quantity',
    'bkht.check': 'Check',
    'bkht.price': 'Price',
    'bkht.contactinfo': 'Fill in the contact information form',
    'bkht.noav': 'Number of allotment',
    'bkht.name': 'Customer name',
    'bkht.phoneno': 'Phone number',
    'bkht.email': 'Email',
    'bkht.note': 'Note',
    'bkht.book': 'Book',

    //booking restaurant
    'bkrtr.title': 'Booking restaurant',
    'bkrtr.bookinginfo': 'Booking information',
    'bkrtr.fromdate': 'Date',
    'bkrtr.fromtime': 'Time',
    'bkrtr.noguest': 'Number of customer',
    'bkrtr.contactinfo': 'Fill in the contact information form',
    'bkrtr.name': 'Customer name',
    'bkrtr.phoneno': 'Phone number',
    'bkrtr.email': 'Email',
    'bkrtr.note': 'Note',
    'bkrtr.book': 'Book',

    //camera
    'camera.title': 'Photo Contribution',

    //cameraemotion
    'cameraemotion.title': 'Emotion detection',

    //toolbox
    'toolbox.rate': 'Rate',
    'toolbox.contribute': 'Photo',
    'toolbox.route': 'Direction',
    'toolbox.call': 'Call',
    'toolbox.addtoplan': 'Add to plan',
    'toolbox.note': 'Note',
    'toolbox.booknow': 'Book',
    'toolbox.see': 'See',
    'toolbox.eat': 'Eat',
    'toolbox.stay': 'Stay',
    'toolbox.explorenearby': 'Explore your nearby',
    'toolbox.promotion': 'Promotions',
    'toolbox.shared':'Share',

    //detail joint part
    'dtp.aboutus': 'ABOUT US',
    'dtp.address': 'Address',
    'dtp.phoneno': 'Phone number',
    'dtp.website': 'Website',
    'dtp.email': 'Email',
    'dtp.description': 'Description',

    //hotel detail
    'htdt.aboutus': 'HOTEL UTILITIES LIST',
    'htdt.explorerht': 'HOTEL ROOM INFORMATION',

    //location lookup - lookup
    'lctlk.title': 'Search',
    'lctlk.search': 'search ...',
    'lctlk.eat': 'Eat',
    'lctlk.stay': 'Stay',
    'lctlk.see': 'See',
    'lctlk.shopping': 'Shopping',
    'lctlk.event': 'Events',
    'lctlk.all': 'All',
    'lctlk.route': 'Direction',
    'lctlk.searchvoice': 'Search by voice',
    'lctlk.service': 'Service',
    'lctlk.price': 'Price',
    'lctlk.type': 'Type',
    'lctlk.address': 'Address',
    'lctlk.area': 'Area',
    'lctlk.seen': 'Seen',

    // login page
    'login.form.title': 'Login',
    'login.form.back': 'Back',
    'login.form.username': 'Username',
    'login.form.password': 'Password',
    'login.form.submitButton': 'Login',
    'login.form.loginFacebook': 'Login with Facebook',
    'login.form.loginGoogle': 'Login with Google',
    'login.form.createButton': 'Register',
    'token.wrongUsernameOrPassword': 'Wrong username or password.',
    'login.missingusernameorpassword': 'Missing username or password.',
    'login.fail.title': 'Fail to Login.',
    'token.unitCodeNotFound': 'Unidentified your unit code.',
    'token.errorWhenCreated': 'Cannot created your account.',
    'token.providerId': 'Failed to authorize your account from social network.',
    'token.missingProviderOrEmail': 'Failed to find your social network.',
    'token.wrongEmail': 'Wrong email format',
    'token.dupplicateEmail': 'Your email has been used. Please try another.',
    'token.usernameEmpty': 'Username is a required field.',
    'token.dupplicateUsername': 'Your username has been used. Please try another.',
    'token.wrongValidPassword': 'Your password does not meet the requirement of minimum 6 characters.',

    // map page
    'map.title': 'Map',
    'map.see': 'See',
    'map.eat': 'Eat',
    'map.stay': 'Stay',
    'map.shop': 'Shop',
    'map.all': 'All',
    'map.other': 'Other',
    'map.search': 'Search',
    'map.showall': 'Show all',
    'map.searchingplace': 'Search',
    'map.address': 'Address',
    'map.advancedsearch': 'Advanced Search',
    'map.type': 'Place Type',
    'map.nearby': 'Nearby',
    'map.direction': 'Direction',
    'map.range': 'Search range',
    'map.distance': 'Distance',
    'map.service': 'Service',
    'map.hobby': 'Travel hobby',
    'map.place': 'Travel place',
    'map.rateofgam': 'Rate from customers and mangement unit',
    'map.pointrange': 'Point range',
    'map.any': 'Any',
    'map.lower': 'Lowwer than',
    'map.higher': 'Higher than',
    'map.free': 'Free',
    'map.fee': 'Fee',
    'map.price': 'Price',
    'map.pricerange': 'Price range',
    'map.startsearch': 'Start Searching',
    'map.placel': 'See',
    'map.hotel': 'Eat',
    'map.restaurant': 'Stay',
    'map.map': 'Map',
    'map.cammode': 'Camera Map',
    'map.seemore': 'See more',
    'map.route': 'Route',

	//notice-list
    'nl.title': 'Notice',
    'nl.readmore': 'Content',

    // event page
    'eventpage.title': 'Hot events',
    'eventpage.morePage': 'See more',

    //event detail
    'ed.introduction': 'INTRODUCTION',
    'ed.address': 'Location',
    'ed.occur': 'Occur time',
    'ed.from': 'From',
    'ed.to': 'to',
    'ed.operationtime': 'Operation Time',
    'ed.content': 'CONTENT',

    //exchange rate
    'er.title': 'Exchange Rate',
    'er.currency': 'Choose exchange rate',
    'er.buy': 'Buy',
    'er.transfer': 'Transfer',
    'er.sell': 'Sell',
    'er.board_title': 'Exchange Rates',
    'er.exchange_value': 'Exchange value',
    'er.exchange': 'Exchange',
    'er.chooseCC': 'Choose Currency',

    //map quick booking
    'mapqb.showdetail':'See more',
    'mapqb.showneaby':'Explore your nearby',

    //map route
    'mapqb.route': 'Direction',
    'mapqb.range': 'Distance',
    'mapqb.time': 'Time',
    'mapqb.updateroute': 'Update Direction',

    //plan
    'plan.title': 'Plan',
    'plan.fromdate': 'Arrival date',
    'plan.todate': 'Leaving date',
    'plan.hobby': 'Travel hobby',
    'plan.tourtype': 'Tour type',
    'plan.relax': 'Relaxed',
    'plan.normal': 'Normal',
    'plan.full': 'Full',
    'plan.create': 'Create Plan',

    //plan add location
    'pal.title': 'Choose place to add',
    'pal.search': 'Search',
    'pal.mustsee': 'Must see',
    'pal.mysaved': 'My saved',
    'pal.neededplace': 'Search',
    'pal.all': 'All',
    'pal.shop': 'Shopping',
    'pal.eat': 'Eat',
    'pal.see': 'See',
    'pal.repimg': 'Representative image',
    'pal.seemore': 'See more',
    'pal.area': 'Area',

    //plan choice
    'pc.title': 'Choose plan to add',
    'pc.createnew': 'Create new plan',
    'pc.createnewtoadd': 'Create a new one to add',
    'pc.fromdate': 'From',
    'pc.todate': 'to',

    //plan date choice
    'pdc.title': 'Choose a date to add',
    'pdc.choosefromhistory': 'Choose a date to add',
    'pdc.day': 'Day',
    'pdc.place': 'place',
    'pdc.repimg': 'Representative image',
    'pdc.choose': 'Choose',
    'pdc.errorexist': 'Place is already in plan',

    //plan date detail
    'pdd.back': 'Back',
    'pdd.editplan': 'Modify plan date',
    'pdd.see': 'See',
    'pdd.route': 'Route',
    'pdd.add': 'Add',
    'pdd.place': 'place',
    'pdd.swap': 'Swap',
    'pdd.twoplace': '2 places',
    'pdd.repimg': 'Representative image',
    'pdd.price': 'Price',
    'pdd.info': 'See more',
    'pdd.direct': 'Direction',

    //plan date edit
    'pde.modify': 'Modify',
    'pde.createnew': 'Create',
    'pde.create': 'Create',
    'pde.savechange': 'Save',
    'pde.recommendedplan': 'Recommended',
    'pde.sharedplan': 'Shared Plans',
    'pde.arrivaldate': 'Arrival Date',
    'pde.dayl': 'day',
    'pde.place': 'place',
    'pde.dayu': 'Day',
    'pde.repimg': 'Representative image',
    'pde.seemore': 'See more',
    'pde.addday': 'Add a day',
    'pde.share': 'Share',
    'pde.unshare': 'Unshare',

    //plan detail
    'pd.reference': 'Reference',
    'pd.modify': 'Modify',
    'pd.dayl': 'day',
    'pd.arrivaldate':'Arrival Date',
    'pd.place': 'place',
    'pd.fromdate': 'Arrival date',
    'pd.dayu': 'Day',
    'pd.repimg': 'Representative image',
    'pd.seemore': 'See more',

    //plan direction
    'pdirect.route': 'Route',
    'pdirect.departure': 'Departure',
    'pdirect.choosedeparture': 'Choose departure',
    'pdirect.destination': 'Destination',
    'pdirect.choosedestination': 'Choose destination',
    'pdirect.direction': 'Direction',
    'pdirect.distance': 'Distance',
    'pdirect.time': 'Time',

    //plan list
    'pl.title': 'Choose a proper plan with your intent',
    'pl.recommendedplan': 'Recommended',
    'pl.sharedplan': 'Shared Plans',
    'pl.description': 'Let enjoy a nice tour at ' + Parameter.cityName_EN,
    'pl.dayl': 'day',

    //plan new empty
    'pne.title': 'Create a new plan',
    'pne.place': 'Place',
    'pne.datefrom': 'Arrival date',
    'pne.dateto': 'Leaving date',
    'pne.note': 'Note',
    'pne.hobby': 'Travel Hobby',
    'pne.relax': 'Relaxed',
    'pne.normal': 'Normal',
    'pne.full': 'Full',
    'pne.createnew': 'Create a plan',

    //plan saved list
    'psl.title': 'History of plan',
    'psl.fromdate': 'Arrival date',
    'psl.todate': 'Leaving date',
    'psl.createddate': 'Created date',

    //planv2
    'pv2.title': 'Create A Plan',
    'pv2.place': 'Place',
    'pv2.datefrom': 'Arrival date',
    'pv2.dateto': 'Leaving date',
    'pv2.pluralday': 'Days',
    'pv2.singleday': 'Day',
    'pv2.hobby': 'Travel hobby',
    'pv2.tourtype': 'Tour type',
    'pv2.relax': 'Relaxed',
    'pv2.normal': 'Normal',
    'pv2.full': 'Full',
    'pv2.createnew': 'Create a plan',
    'pv2.viewhistory': 'View plan history',

    // quick booking
    'quickbooking.title': 'Quick Booking',
    'quickbooking.form.title': 'Booking information',
    'quickbooking.form.toDate': 'Check-in date',
    'quickbooking.form.fromDate': 'Check-out date',
    'quickbooking.form.roomFormat': 'Room Format',
    'quickbooking.form.roomType': 'Room Type',
    'quickbooking.form.roomNumber': 'Number of room',
    'quickbooking.form.distance': 'Distance',
    'quickbooking.form.location': 'Location by GPS',
    'quickbooking.form.price': 'Price',
    'quickbooking.form.userInfoTitle': 'Customer information',
    'quickbooking.form.fullName': 'Customer name',
    'quickbooking.form.phone': 'Phone number',
    'quickbooking.form.email': 'Email',
    'quickbooking.form.submit': 'Register',
    'quickplan.form.error.email': 'Wrong email format',
    'quickplan.form.error.name': 'Please input your name',
    'quickplan.form.error.phone': 'Please input your phone number',
    'quickBooking.unknowError': 'Error occur. Please try again later',

    //register
    'register.title': 'Register',
    'register.subtitle': 'Register Account',
    'register.logForm.FirstName': 'Last name',
    'register.logForm.LastName': 'First name',
    'register.logForm.Email': 'Email',
    'register.logForm.UserName': 'Username',
    'register.logForm.Password': 'Password',
    'register.logForm.LanguageId': 'Language',
    'register.logForm.submitButton': 'Register',

    //restaurant detail
    'rdt.back': 'Back',
    'rdt.addtoplan': 'Add to a plan',
    'rdt.call': 'Call',
    'rdt.rate': 'Rate',
    'rdt.takephoto': 'Photo',
    'rdt.route': 'Direction',
    'rdt.booking': 'Book',
    'rdt.aboutus': 'ABOUT US',
    'rdt.address': 'Address',
    'rdt.operationtime': 'Operation time',
    'rdt.phoneno': 'Phone number',
    'rdt.website': 'Website',
    'rdt.email': 'Email',
    'rdt.description': 'Description',
    'rdt.specialties': 'Restaurant Specialties',
    'rdt.unupdated': 'Products are not updated',
    'rdt.explorenearby': 'Explore your nearby',
    'rdt.price' : "Price",
    'rdt.doCameraTour': 'Go arround the place (Camera View)',
    'rdt.specialties2': 'Productivity',

    //search location
    'sl.title': 'Recommended travel place',
    'sl.searchplace': 'Search',
    'sl.seemore': 'See more',
    'sl.notfound': 'No result meets requirement',

    //shop detail
    'sd.title': 'Note',
    'sd.note': 'Note',
    'sd.call': 'Call',
    'sd.rate': 'Rate',
    'sd.takephoto': 'Photo',
    'sd.direction': 'Direction',
    'sd.introduction': 'INTRODUCTION',
    'sd.address': 'Address',
    'sd.phoneno': 'Phone number',
    'sd.website': 'Website',
    'sd.email': 'Email',
    'sd.description': 'Description',
    'sd.product': 'List products',

    //translate language
    'tl.title': 'Dictionary by Voice',
    'tl.content': 'Content',
    'tl.languagenotfound': 'No language chosen',
    'tl.result': 'Result',
    'tl.chooselang': 'Choose a language',
    'tl.cancel': 'Cancel',

    //shopping
    'shp.title': 'Shopping',
    'shp.type': 'Type',
    'shp.all': 'All',
    'shp.noresult': 'No result meets requirement',

    //sight-seeing
    'ss.back': 'Back',
    'ss.addtoplan': 'Add to plan',
    'ss.note': 'Note',
    'ss.call': 'Call',
    'ss.rate': 'Rate',
    'ss.takephoto': 'Photo',
    'ss.route': 'Direction',
    'ss.introduction': 'INTRODUCTION',
    'ss.address': 'Address',
    'ss.operationtime': 'Operation Time',
    'ss.phoneno': 'Phone Number',
    'ss.website': 'Website',
    'ss.email': 'Email',
    'ss.description': 'Description',
    
    //tour guide
    'tgs.title': 'Lookup to verify the tour guide.',
    'tgs.searchByText': 'Search',
    'tgs.searchByScan': 'Scan card',
    'tgs.searchWithName': 'Tour guide name',
    'tgs.searchWithCardCode': 'Tour guide ID number',
    'tgs.name': 'Full name',
    'tgs.cardcode': 'Card number',
    'tgs.status': 'Card status',
    'tgs.expired_date': 'Expired date',
    'tgs.issue_place': 'Issued by',
    'tgs.langs': 'Language',
    'tgs.experience': 'Experience',
    'tgs.type': 'Card type',
    'tgs.errorScan': 'No result was found.',

    //user
    'user.title': 'Account',
    'user.hobby': 'Hobby',
    'user.hobbydescrition': 'Choose your travel hobby',
    'user.planhistory': 'Plan history',
    'user.planhistorydescription': 'See your plan history',
    'user.bookinghistory': 'Booking history',
    'user.bookinghistorydescription': 'See your booking history',
    'user.mysaved': 'My saved',
    'user.mysaveddescription': 'See your note travel place',
    'user.mynote': 'My note',
    'user.mynotedescription': 'See travel place that you have noted',

    //userbooking
    'userbooking.title': 'History booking',
    'userbooking.fromdate': 'Check-in date',
    'userbooking.dayu': 'Day',
    'userbooking.todate': 'Check-out date',
    'userbooking.at': 'at',

    //user change info
    'uci.title': 'Change your user information',
    'uci.changeinfo': 'change your user information',
    'uci.fname': 'First name',
    'uci.lname': 'Last name',
    'uci.address': 'Address',
    'uci.phoneno': 'Phone number',
    'uci.modify': 'Save changes',
    'uci.changepwd': 'Change your password',
    'uci.oldpwd': 'Old password',
    'uci.newpwd': 'New password',
    'uci.confirmnewpwd': 'Confirm new password',
    'uci.btnchangepwd': 'Change password',
    'uci.tabtitle': 'Choose info you want to change',
    'uci.errorfieldrequired': "Field \"Firstname\" và \"Lastname\" are required",
    'uci.successupdateduser': "Successfully updated your account's infomation",
    'uci.wrongOldPassword': "Wrong old password",
    'uci.wrongConfirmPassword': "Wrong confirm password",
    'uci.failupdateduser': "An error occur when updating information. Please try again later.",
    'uci.duppicationphone': 'This phone number has already been used for registering. Please try again with another one.',

    //user complaint
    'ucp.title': 'User Complaint',
    'ucp.subtitle': 'Title',
    'ucp.placetoreport': 'Complaining place',
    'ucp.content': 'Content',
    'ucp.post': 'Submit',
    'ucp.clue': 'This complaint will be used to report and suggest to a management unit about the service quality of ' + Parameter.cityName_EN,
    'ucp.telephone': 'Phone No.',
    'ucp.required': 'Required',
    'ucp.optional': 'Optional',
    'ucp.fullname': 'Full name',
    'ucp.requiredField': 'Please choose at least one re',
    'ucp.sendSuccess': 'Your reviews have been received and send to the responsible unit. Thank you for using our services.',
    'ucp.warning': 'Please fill all required field.',

    //user feedback detail
    'ufd.title': 'Report travel place',
    'ufd.content': 'Content',
    'ufd.post': 'Submit',

    //user hobby
    'ub.title': 'Travel Hobby',

    //user images
    'ui.title': 'Image of ',

    //user note
    'un.title': 'Note about',
    'un.description': 'Your note',

    //user rate
    'ur.title': 'Rate',
    'ur.content': 'Content',
    'ur.point': 'Point',
    
    //user wishlist - mysaved
    'mysaved.title': 'Travel place suggestion',
    'mysaved.mustsee': 'Must see',
    'mysaved.mysaved': 'My saved',
    'mysaved.direction': 'Direction',
    'mysaved.remove': 'Remove',
    'mysaved.address': 'Address',

    //ultility location list
    'ull.title': 'Utilities Service List',
    'ull.route': 'Direction',

    //utilities type list
    'utl.title': 'Utilities Service',
    'utl.weather': 'Weather',
    'utl.translate': 'Dictionary by voice', 
    'utl.tourguide': 'Tourguide',

    //weather
    'weather.title': 'Weather forecast',
    'weather.followingdays': 'Weather Forecast for the next 5 days',
    'weather.high': 'High',
    'weather.low': 'Low',

    //tour-ar
    'tar.title': 'Visit place using camera mode',
    'tar.loading': 'Loading and asyncing data',

    //list-note
    'note-list.title': 'My notes',
    'note-list.viewnote': 'View note',

    'error.valid.required': 'Cannot by empty',
    'error.valid.minLength': 'Minimum {{0}} character(s)',
    'error.valid.maxLength': 'Maximum {{0}} character(s)',
    'error.valid.minValue': 'Input more than {{0}}',
    'error.valid.maxValue': 'Input less than {{0}}',
    'error.valid.dateFormat': 'Wrond format',
    'form.button.submit': 'Save change',
    'form.button.reset': 'Reset form',
    'form.button.close': 'Cancel',
    'action.success': 'Successful',
    'action.error': 'Failed',

    //trang quickbooking - error popup
    'map.cancelButton': 'Cancel',
    'quickBooking.noResult': 'No proper hotel found',
    'quickBooking.noResultNext': 'No proper hotel found. Do you want to wide open your search?',

    //locales.properties
    'network.error': 'Disconnect to server. Please try again',
    'network.title': 'Error',
    'info.title': 'Information',
    'info.baotri': 'This component is currently maintained and will be back soon.',
    'info.gps': 'There is a change of location permission. Please wait for system to get your surroundings.',
    'info.deviceonly': 'Your device\'s GPS is not responding. Please use "High Accuracy" mode.(Use GPS, Wi-Fi and Mobile Networks)',
    'warning.title': 'Warning',
    'error.title': 'Failed',
    'gps.error': 'GPS is now off that leads to the system to work incorrectly. Please turn on the GPS for the system to work correctly',
    'gps.error1': 'GPS is not allowed for this application. Please allow this app in setting.',
    'mysaved.tick': 'Thêm yêu thích',
    'mysaved.untick': 'Bỏ yêu thích',

     //Joint part
    'info.from': 'Từ',
    'info.to': 'đến',

    "errors.UserName.duplicate": "The user is no longer available. Please use anothers.",
    'error.invaliddatefrom': 'Cannot choose date bofore the current',
    'error.invalidmaximum': 'Exceeding maximum day of a plan (4 days)',
    'error.invalidmax7': "Exceeding maximum day of a plan (7 days)",
    'error.invalidmin1': "Minimum day is one day",
    'error.invalidoperation': 'Time is set before operation time. Please try again.',
    'error.invalidclosetime': 'Time is set after close time. Please try again.',
    'error.invalidtime': 'Invalid time set. Please try another one.',
    'error.suggesttime': 'The setting time is not proper. Proper time is ',
    'error.invalidsame': "Place from and to cannot be the same.",
    'error.invalidfromto': 'Check-out date must be greater than current date at least one day',
    'error.differfromto': 'The difference between check-out date and check-in date cannot be over 4 days',
    'error.invalidmail': "Wrong email format.",
    'error.requestmorethanav': "Requested room quantity is more than available room. Please try another type.",
    'token.usernameHaveSpecialString': 'Username is NOT ENOUGH 6 characters or contains UPPERCASE character or OTHER SPECIAL characters. Please check it.',
    'error.invalidnumber': 'Invalid Number Format of Quantity',
    'error.quantityzero': 'Quantity must higher than 0',
	
    'warning.changetime': 'Adding this place make the general time of the plan to be modify. Please check the plan again.',
    'warning.deleteplan': "Do you want to remove this plan day?",
    'warning.savechange': "There is a change in plan. Do you want save the change?",
    'warning.suggestlogin': 'Please login to use the recommended plan',
    'warning.changeplanname': 'Change plan name',
    'warning.inputname': "New name for your plan",
    'warning.checkAV': "Please check allotment of the type you need to book",
    'warning.outoforder': "Needed room type is not available. Please try another.",
    'warning.fillform': "Please full fill the needed information field.",
    'warning.timenotexpire': "Time to wait from last quickbooking is 1 minute. Please wait.",

    'info.swapping': 'Choose two place that you need to swap',
    'info.saved': "The modify has been saved.",
    'info.successfulcreate': "Create tour is successful. Please check it in the plan history to continue modifying.",
    'info.successfulcreatesuggest': 'The plan has been suggested. Do you want to save it?',
    'info.succesfullymodify': "Plan is successfully saved. Please check it in the plan history to continue modifying.",
    'info.requestcreate': "You have created a new plan. Do you want to save it?",
    'info.successbkr': "Booking successful. Request has been sent",
    'info.successbkt': "Booking successful. Request has been sent",
    'info.emotion': 'Your current emotion is analysed as below ',
    'info.successfulregister': "You have successfully registered an account. Please login and learn more features.",

    //register
    'register.logForm.Address': 'Address',
    'register.logForm.Phone': 'Phone number',
    'register.logForm.ConfirmPassword': 'Confirm your password',

    //Emotion
    "anger": "Anger",
    "fear": "Scary",
    "happiness": "Happiness",
    "neutral": "Normal",
    "sadness": "Sadness",
    "surprise": "Surprise",

    // Time translate
    'data.night': 'night(s)',
    'data.hour': 'hour',
    'data.hours': 'hours',
    'data.day': 'day',
    'data.days': 'days',
    'data.minutes': 'minutes',
    'data.minute': 'minute',
    'data.years': 'year(s)',
    'data.month': 'month',
    'data.months': 'months',
    
    'recognitioning': 'Recording',
    'recognitioning.stop': 'Stop',

    'slideshow.title': 'Quick view for place.',
    'lctlk.dishes': 'Dishes',
    'lctlk.session': 'Session',
    'overview.entertainment': 'Entertainment',
    'overview.nightlife': 'Nightlife',
    'lctlk.entertainment':'Entertainment',

    "newweather.title": "Weather forecast for " + Parameter.cityName_EN,

    'w200': 'thunderstorm with light rain',
    'w201': 'thunderstorm with rain',
    'w202': 'thunderstorm with heavy rain',
    'w210': 'light thunderstorm',
    'w211': 'thunderstorm',
    'w212': 'heavy thunderstorm',
    'w221': 'ragged thunderstorm',
    'w230': 'thunderstorm with light drizzle',
    'w231': 'thunderstorm with drizzle',
    'w232': 'thunderstorm with heavy drizzle',
    'w300': 'light intensity drizzle',
    'w301': 'drizzle',
    'w302': 'heavy intensity drizzle',
    'w310': 'light intensity drizzle rain',
    'w311': 'drizzle rain',
    'w312': 'heavy intensity drizzle rain',
    'w313': 'shower rain and drizzle',
    'w314': 'heavy shower rain and drizzle',
    'w321': 'shower drizzle',
    'w500': 'light rain',
    'w501': 'moderate rain',
    'w502': 'heavy intensity rain',
    'w503': 'very heavy rain',
    'w504': 'extreme rain',
    'w511': 'freezing rain',
    'w520': 'light intensity shower rain',
    'w521': 'shower rain',
    'w522': 'heavy intensity shower rain',
    'w531': 'ragged shower rain',
    'w600': 'light snow',
    'w601': 'snow',
    'w602': 'heavy snow',
    'w611': 'sleet',
    'w612': 'shower sleet',
    'w615': 'light rain and snow',
    'w616': 'rain and snow',
    'w620': 'light shower snow',
    'w621': 'shower snow',
    'w622': 'heavy shower snow',
    'w701': 'mist',
    'w711': 'smoke',
    'w721': 'haze',
    'w731': 'sand, dust whirls',
    'w741': 'fog',
    'w751': 'sand',
    'w761': 'dust',
    'w762': 'volcanic ash',
    'w771': 'squalls',
    'w781': 'tornado',
    'w800': 'clear sky',
    'w801': 'few clouds',
    'w802': 'scattered clouds',
    'w803': 'broken clouds',
    'w804': 'overcast clouds',

    'cal.mon': 'Monday',
    'cal.tue': 'Tuesday',
    'cal.wed': 'Wednesday',
    'cal.thu': 'Thursday',
    'cal.fri': 'Friday',
    'cal.sat': 'Saturday',
    'cal.sun': 'Sunday',

    'forecast.n3': 'Weather forecast for the next 3 hours'
};