import { Parameter } from "../model/Service";

export const LANG_VN_NAME = 'vi';

export const LANG_VN_TRANS = {
    'menu.overview': 'Tổng quan',
    'menu.eventlist': 'Sự kiện',
    'menu.quickbooking': 'Đặt phòng nhanh',
    'menu.planv2': 'Lịch trình',
    'menu.plan': 'Lịch trình',
    'menu.setting': 'Cài đặt',
    'menu.setting-language': 'Ngôn ngữ',
    'menu.setting-language.Vi': 'Tiếng Việt',
    'menu.setting-language.En': 'Tiếng Anh',
    'menu.setting-aboutUs': 'Về chúng tôi',
    'menu.account': 'Tài khoản',
    'menu.emotion': 'Nhận diện cảm xúc',
    'menu.plansaved': 'Lịch trình đã tạo',
    'menu.logoff': 'Đăng xuất',
    'menu.cammode': 'Chế độ tham quan camera',
    'menu.currVersion': 'Phiên bản hiện tại',
    'menu.newslist':'Tin tức',
    'menu.sharedApp':'Chia sẻ ứng dụng',
    'menu.FanPage': 'FanPage',

    //tab
    'tab.overview': 'Tổng quan',
    'tab.mysaved': 'Yêu thích',
    'tab.plan': 'Lịch trình',
    'tab.map': 'Bản đồ',
    'tab.account': 'Tài khoản',

    //overview
    'overviewpage.title': 'Tổng quan',
    'overview.search': 'Tìm kiếm',
    'overview.eat': 'Ẩm thực',
    'overview.stay': 'Nghỉ ngơi',
    'overview.see': 'Tham quan',
    'overview.shopping': 'Mua sắm',
    'overview.quickbooking': 'Quick booking',
    'overview.hotline': 'Liên hệ',
    'overview.complaints': 'Phản ánh',
    'overview.popular': 'Điểm thu hút khách',
    'overview.promotion': 'Khuyến mãi',
    'overview.utilities': 'Tiện ích',
    'overview.exchangerate': 'Tỉ giá',
    'overview.event': 'Sự kiện',
    'overview.culture': 'Đặc sắc',
    'overview.advice': 'Lời khuyên',
    'overview.move': 'Di chuyển',
    'overview.weather': 'Thời tiết',
    'overview.karaoke': 'Giải trí',
    'overview.titleContact': 'Thông tin liên hệ',
    'overview.bodySupportInfo': 'Thông tin hỗ trợ',
    'overview.bodyHotline': 'Hotline',
    'overview.bodyAddress': 'Địa chỉ',
    'overview.bodyWebsite': 'Website',
    'overview.detailpromotion': 'Chi tiết khuyến mãi',
    'overview.saleoff': 'Giảm giá đến',

    //advice
    'advice-list.title-1': 'Những lời khuyên khi đến '+Parameter.cityName_VN,
    'advice-list.title-2': 'Những tác phẩm nghệ thuật đặc sắc',
    'advice-list.title-3': 'Những video clip về '+Parameter.cityName_VN,
    'advice-list.title-4': 'Những di sản phi vật thể đặc sắc',
    'advice-list.tab-poem': 'Tác phẩm nghệ thuật',
    'advice-list.tab-video': 'Video Clip',
    'advice-list.tab-historicalitem': 'Di sản phi vật thể',

    //booking hotel
    'bkhtdt.title': 'Chi tiết booking',
    'bkhtdt.contact': 'Liên hệ',
    'bkhtdt.customer_name': 'Khách hàng',
    'bkhtdt.phoneno': 'Số điện thoại',
    'bkhtdt.email': 'Email',
    'bkhtdt.bkinfo': 'Thông tin booking',
    'bkhtdt.time': 'Thời gian',
    'bkhtdt.place': 'Địa điểm',
    'bkhtdt.nocustomer': 'Số lượng khách',
    'bkhtdt.createtime': 'Thời điểm tạo booking',
    'bkhtdt.price': 'Giá',
    'bkhtdt.serviceprice': 'Giá dịch vụ',
    'bkhtdt.total': 'Tổng tiền',
    'bkhtdt.noroom': 'Số lượng phòng',

    //booking hotel
    'bkht.title': 'Đặt phòng khách sạn',
    'bkht.bookinginfo': 'Thông tin đặt phòng',
    'bkht.fromdate': 'Chọn ngày đến',
    'bkht.todate': 'Chọn ngày đi',
    'bkht.roomtype': 'Chọn loại phòng',
    'bkht.roomformat': 'Chọn dạng phòng',
    'bkht.noroom': 'Số lượng phòng',
    'bkht.checkav': 'Kiểm tra số lượng phòng còn lại',
    'bkht.check': 'Kiểm tra',
    'bkht.price': 'Giá',
    'bkht.contactinfo': 'Nhập thông tin liên hệ',
    'bkht.noav': 'Số phòng trống',
    'bkht.name': 'Họ và tên',
    'bkht.phoneno': 'Số điện thoại',
    'bkht.email': 'Địa chỉ email',
    'bkht.note': 'Ghi chú',
    'bkht.book': 'Đặt phòng',

    //booking restaurant
    'bkrtr.title': 'Đặt bàn nhà hàng',
    'bkrtr.bookinginfo': 'Thông tin đặt bàn',
    'bkrtr.fromdate': 'Ngày đặt bàn',
    'bkrtr.fromtime': 'Giờ đặt bàn',
    'bkrtr.noguest': 'Số lượng khách',
    'bkrtr.contactinfo': 'Nhập thông tin liên hệ',
    'bkrtr.name': 'Họ và tên',
    'bkrtr.phoneno': 'Số điện thoại',
    'bkrtr.email': 'Địa chỉ email',
    'bkrtr.note': 'Ghi chú',
    'bkrtr.book': 'Đặt bàn',

    //camera
    'camera.title': 'Đóng góp hình ảnh',

    //cameraemotion
    'cameraemotion.title': 'Nhận diện cảm xúc',

    //toolbox
    'toolbox.rate': 'Đánh giá',
    'toolbox.contribute': 'Đóng góp',
    'toolbox.route': 'Chỉ đường',
    'toolbox.call': 'Gọi',
    'toolbox.addtoplan': 'Thêm vào lịch trình',
    'toolbox.note': 'Ghi chú',
    'toolbox.booknow': 'Đặt ngay',
    'toolbox.see': 'Tham quan',
    'toolbox.eat': 'Ăn uống',
    'toolbox.stay': 'Nghỉ ngơi',
    'toolbox.explorenearby': 'Khám phá những địa điểm lân cận',
    'toolbox.shared':'Chia sẻ',
    'toolbox.promotion': 'Chương trình khuyến mãi',

    //detail joint part
    'dtp.aboutus': 'VỀ CHÚNG TÔI',
    'dtp.address': 'Địa chỉ',
    'dtp.phoneno': 'Số điện thoại',
    'dtp.website': 'Website',
    'dtp.email': 'Email hỗ trợ khách hàng',
    'dtp.description': 'Mô tả',

    //hotel detail
    'htdt.aboutus': 'NHỮNG TIỆN NGHI ĐƯỢC ƯA THÍCH',
    'htdt.explorerht': 'KHÁM PHÁ PHÒNG KHÁCH SẠN',

    //location lookup - lookup
    'lctlk.title': 'Tìm kiếm địa danh',
    'lctlk.search': 'Tìm kiếm ...',
    'lctlk.eat': 'Ăn uống',
    'lctlk.stay': 'Nghỉ ngơi',
    'lctlk.see': 'Tham quan',
    'lctlk.shopping': 'Cửa hàng',
    'lctlk.event': 'Sự kiện',
    'lctlk.all': 'Tất cả',
    'lctlk.route': 'Chỉ đường',
    'lctlk.searchvoice': 'Tìm kiếm bằng giọng nói',
    'lctlk.service': 'Dịch vụ',
    'lctlk.price': 'Giá',
    'lctlk.type': 'Loại',
    'lctlk.address': 'Địa chỉ',
    'lctlk.area': 'Khu vực',
    'lctlk.seen': 'Đã xem',

    // login page
    'login.form.title': 'Đăng nhập',
    'login.form.back': 'Back',
    'login.form.username': 'Tên đăng nhập',
    'login.form.password': 'Mật khẩu',
    'login.form.submitButton': 'Đăng nhập',
    'login.form.loginFacebook': 'Đăng nhập với Facebook',
    'login.form.loginGoogle': 'Đăng nhập với Google',
    'login.form.createButton': 'Đăng ký',
    'token.wrongUsernameOrPassword': 'Sai tên đăng nhập hoặc mật khẩu!',
    'login.missingusernameorpassword': 'Chưa nhập tên đăng nhập hoặc mật khẩu!',
    'login.fail.title': 'Đăng nhập thất bại',
    'token.errorWhenCreated': 'Không tạo được tài khoản.',
	'token.unitCodeNotFound': 'Mã thông tin không xác định',
    'token.providerId': 'Không thể kết nối đến tài khoản của bạn trên mạng xã hội.',
    'token.missingProviderOrEmail': 'Không thể tìm thấy mạng xã hội này.',
    'token.wrongEmail': 'Sai định dạng email',
    'token.dupplicateEmail': 'Email này đã được sử dụng. Vui lòng sử dụng email khác.',
    'token.usernameEmpty': 'Username không thể bỏ trống',
    'token.dupplicateUsername': 'Username này đã được sử dụng. Vui lòng sử dụng username khác.',
    'token.wrongValidPassword': 'Mật khẩu không đúng yêu cầu. Vui lòng nhập trên 6 kí tự',

    // map page
    'map.title': 'Bản đồ',
    'map.see': 'Tham quan',
    'map.eat': 'Ăn Uống',
    'map.stay': 'Nghỉ ngơi',
    'map.shop': 'Mua sắm',
    'map.all': 'Tất cả',
    'map.other': 'Khác',
    'map.search': 'Tìm kiếm',
    'map.showall': 'Hiển thị tất cả',
    'map.searchingplace': 'Địa điểm cần tra cứu',
    'map.address': 'Địa chỉ',
    'map.nearby': 'Lân cận',
    'map.direction': 'Chỉ đường',
    'map.advancedsearch': 'Tìm kiếm nâng cao',
    'map.type': 'Loại địa điểm',
    'map.service': 'Dịch vụ',
    'map.range': 'Bán kính tìm kiếm',
    'map.distance': 'Khoảng cách',
    'map.hobby': 'Sở thích du lịch',
    'map.place': 'Địa điểm du lịch',
    'map.rateofgam': 'Theo đánh giá của người dùng và cơ quan quản lý',
    'map.pointrange': 'Thang điểm',
    'map.any': 'Bất kỳ',
    'map.lower': 'Dưới',
    'map.higher': 'Trên',
    'map.free': 'Miễn phí',
    'map.fee': 'Trả phí',
    'map.price': 'Theo giá',
    'map.pricerange': 'Khoảng giá',
    'map.startsearch': 'Bắt đầu tìm kiếm',
    'map.placel': 'địa điểm tham quan',
    'map.hotel': 'khách sạn, nhà nghỉ',
    'map.restaurant': 'nhà hàng, quán ăn',
    'map.map': 'Bản đồ',
    'map.cammode': 'Bản đồ Camera',
    'map.seemore': 'Chi tiết',
    'map.route': 'Chỉ đường',

    //notice-list
    'nl.title': 'Thông báo',
    'nl.readmore': 'Nội dung',

    // event page
    'eventpage.title': 'Sự kiện nổi bật',
    'eventpage.morePage': 'Xem thêm',

    //event detail
    'ed.introduction': 'Giới thiệu',
    'ed.address': 'Địa điểm',
    'ed.occur': 'Thời gian diễn ra',
    'ed.from': 'Từ',
    'ed.to': 'đến',
    'ed.operationtime': 'Giờ mở cửa',
    'ed.content': 'Nội dung',

    //exchange rate
    'er.title': 'Chuyển đổi tiền tệ',
    'er.currency': 'Chọn ngoại tệ',
    'er.buy': 'Mua vào',
    'er.transfer': 'Giao dịch',
    'er.sell': 'Bán ra',
    'er.board_title': 'Tỷ giá ngoại tệ',
    'er.exchange_value': 'Giá trị quy đổi',
    'er.exchange': 'Quy đổi',
    'er.chooseCC': 'Chọn ngoại tệ',

    //map quick booking
    'mapqb.showdetail':'Xem chi tiết',
    'mapqb.showneaby':'Hiển thị địa điểm xung quanh',

    //map route
    'mapqb.route': 'Chỉ đường',
    'mapqb.range': 'Khoảng cách',
    'mapqb.time': 'Thời gian',
    'mapqb.updateroute': 'Cập nhật chỉ đường',

    //plan
    'plan.title':'Lịch trình',
    'plan.fromdate':'Ngày bắt đầu',
    'plan.todate':'Ngày kết thúc',
    'plan.hobby':'Sở thích du lịch',
    'plan.tourtype':'Loại tour',
    'plan.relax':'Thư giãn',
    'plan.normal':'Bình thường',
    'plan.full':'Đầy đủ',
    'plan.create':'Tạo lịch trình',

    //plan add location
    'pal.title':'Chọn địa điểm thêm vào',
    'pal.search':'Tìm kiếm',
    'pal.mustsee':'Gợi ý',
    'pal.mysaved':'Yêu thích',
    'pal.neededplace':'Địa điểm cần tìm',
    'pal.all':'Tất cả',
    'pal.shop':'Mua sắm',
    'pal.eat':'Ăn uống',
    'pal.see':'Tham quan',
    'pal.repimg':'hình đại diện',
    'pal.seemore':'Xem thêm',
    'pal.area': 'Khu vực',

    //plan choice
    'pc.title': 'Chọn lịch trình muốn thêm',
    'pc.createnew': 'Thêm vào lịch trình mới',
    'pc.createnewtoadd': 'Tạo một lịch trình mới để thêm vào',
    'pc.fromdate': 'Từ',
    'pc.todate': 'Đến',

    //plan date choice
    'pdc.title': 'Chọn 1 ngày của lịch trình',
    'pdc.choosefromhistory': 'Chọn 1 ngày của lịch trình',
    'pdc.day': 'Ngày',
    'pdc.place': 'địa điểm',
    'pdc.repimg': 'Ảnh đại diện',
    'pdc.choose': 'Chọn',
    'pdc.errorexist': 'Địa điểm đã có sẵn trong lịch trình',

    //plan date detail
    'pdd.back': 'Back',
    'pdd.editplan': 'Chỉnh sửa lịch trình ngày',
    'pdd.see': 'Xem',
    'pdd.route': 'lộ trình',
    'pdd.add': 'Thêm',
    'pdd.place': 'địa điểm',
    'pdd.swap': 'Hoán đổi',
    'pdd.twoplace': 'vị trí',
    'pdd.repimg': 'Ảnh đại diện',
    'pdd.price': 'Giá',
    'pdd.info': 'Thông tin',
    'pdd.direct': 'Chỉ đường',

    //plan date edit
    'pde.modify': 'Chỉnh sửa',
    'pde.createnew': 'Tạo mới',
    'pde.create': 'Tạo',
    'pde.savechange': 'Lưu',
    'pde.recommendedplan': 'Lịch trình đề xuất',
    'pde.sharedplan': 'Lịch trình chia sẻ',
    'pde.dayl': 'ngày',
    'pde.arrivaldate': 'Từ ngày',
    'pde.place': 'địa điểm',
    'pde.dayu': 'Ngày',
    'pde.repimg': 'Ảnh đại diện',
    'pde.seemore': 'Xem chi tiết',
    'pde.addday': 'Thêm ngày',
    'pde.share': 'Share',
    'pde.unshare': 'Unshare',

    //plan detail
    'pd.reference':'Tham khảo',
    'pd.modify':'Thay đổi',
    'pd.dayl':'ngày',
    'pd.arrivaldate':'Từ ngày',
    'pd.place':'địa điểm',
    'pd.fromdate':'Từ ngày',
    'pd.dayu':'Ngày',
    'pd.repimg':'Ảnh đại diện',
    'pd.seemore':'Xem chi tiết',

    //plan direction
    'pdirect.route':'Lộ trình',
    'pdirect.departure':'Điểm bắt đầu',
    'pdirect.choosedeparture':'Chọn điểm bắt đầu',
    'pdirect.destination':'Điểm đến',
    'pdirect.choosedestination':'Chọn điểm đến',
    'pdirect.direction':'Chỉ đường',
    'pdirect.distance':'Khoảng cách',
    'pdirect.time':'Thời gian',

    //plan list
    'pl.title':'Tùy chọn 1 tour phù hợp',
    'pl.recommendedplan':'Lịch trình đề xuất',
    'pl.sharedplan':'Lịch trình chia sẻ',
    'pl.description':'Hãy cùng tận hưởng giây phút vui vẻ của cuộc sống để du lịch tại '+Parameter.cityName_VN,
    'pl.dayl':'ngày',

    //plan new empty
    'pne.title':'Tạo lịch trình mới',
    'pne.place':'Địa điểm du lịch',
    'pne.datefrom':'Ngày bắt đầu',
    'pne.dateto':'Ngày kết thúc',
    'pne.note':'Ghi chú',
    'pne.hobby':'Sở thích du lịch',
    'pne.relax':'Thư giãn',
    'pne.normal':'Bình thường',
    'pne.full':'Đầy đủ',
    'pne.createnew':'Tạo lịch trình',

    //plan saved list
    'psl.title': 'Danh sách lịch trình đã tạo',
    'psl.fromdate': 'Từ ngày',
    'psl.todate': 'Đến ngày',
    'psl.createddate': 'Ngày tạo',

    //planv2
    'pv2.title': 'Lịch trình',
    'pv2.place': 'Địa điểm du lịch',
    'pv2.datefrom': 'Ngày bắt đầu',
    'pv2.dateto': 'Số ngày',
    'pv2.pluralday': 'Ngày',
    'pv2.singleday': 'Ngày',
    'pv2.hobby': 'Sở thích du lịch',
    'pv2.tourtype': 'Loại tour',
    'pv2.relax': 'Thư giãn',
    'pv2.normal': 'Bình thường',
    'pv2.full': 'Đầy đủ',
    'pv2.createnew': 'Tạo lịch trình',
    'pv2.viewhistory': 'Xem lại lịch sử',

    // quick booking
    'quickbooking.title': 'Quick Booking',
    'quickbooking.form.title': 'Thông tin đặt phòng',
    'quickbooking.form.toDate': 'Từ ngày',
    'quickbooking.form.fromDate': 'Đến ngày',
    'quickbooking.form.roomFormat': 'Dạng phòng',
    'quickbooking.form.roomType': 'Loại phòng',
    'quickbooking.form.roomNumber': 'Số phòng',
    'quickbooking.form.distance': 'Khoảng cách',
    'quickbooking.form.location': 'Vị trí',
    'quickbooking.form.price': 'Giá',
    'quickbooking.form.userInfoTitle': 'Thông tin người đặt',
    'quickbooking.form.fullName': 'Tên',
    'quickbooking.form.phone': 'SĐT',
    'quickbooking.form.email': 'Email',
    'quickbooking.form.submit': 'Đăng kí',
    'quickplan.form.error.email': 'Sai định dạng Email',
    'quickplan.form.error.name': 'Vui lòng nhập Tên',
    'quickplan.form.error.phone': 'Vui lòng nhập SĐT',
    'quickBooking.unknowError': 'Đã có lỗi xảy ra. Vui lòng thử lại sau!',

    //register
    'register.title': 'Đăng ký',
    'register.subtitle': 'Đăng ký tài khoản',
    'register.logForm.FirstName': 'Tên',
    'register.logForm.LastName': 'Họ',
    'register.logForm.Email': 'Email',
    'register.logForm.UserName': 'Tên đăng nhập',
    'register.logForm.Password': 'Mật khẩu',
    'register.logForm.LanguageId': 'Ngôn ngữ',
    'register.logForm.submitButton': 'Đăng ký',

    //restaurant detail
    'rdt.back': 'Back',
    'rdt.addtoplan': 'Thêm vào lịch trình',
    'rdt.call': 'Gọi',
    'rdt.rate': 'Đánh giá',
    'rdt.takephoto': 'Đóng góp',
    'rdt.route': 'Chỉ đường',
    'rdt.booking': 'Đặt ngay',
    'rdt.aboutus': 'VỀ CHÚNG TÔI',
    'rdt.address': 'Địa chỉ',
    'rdt.operationtime': 'Khung giờ hoạt động',
    'rdt.phoneno': 'Số điện thoại',
    'rdt.website': 'Website',
    'rdt.email': 'Email hỗ trợ khách hàng',
    'rdt.description': 'Mô tả',
    'rdt.specialties': 'Đặc sản nổi tiếng của nhà hàng',
    'rdt.unupdated': 'Chưa cập nhật sản phẩm',
    'rdt.explorenearby': 'Khám phá những địa điểm lân cận',
    'rdt.price' : "Giá",
    'rdt.doCameraTour': 'Tham quan (Chế độ Camera)',
    'rdt.specialties2': 'Sản phẩm phục vụ',

    //search location
    'sl.title': 'Gợi ý địa điểm du lịch',
    'sl.searchplace': 'Địa điểm cần tra cứu',
    'sl.seemore': 'Xem chi tiết',
    'sl.notfound': 'Không tìm thấy kết quả phù hợp',

    //shop detail
    'sd.title': 'Thông tin cửa hàng',
    'sd.note': 'Ghi chú',
    'sd.call': 'Gọi',
    'sd.rate': 'Đánh giá',
    'sd.takephoto': 'Đóng góp',
    'sd.direction': 'Chỉ đường',
    'sd.introduction': 'GIỚI THIỆU',
    'sd.address': 'Địa chỉ',
    'sd.phoneno': 'Số điện thoại',
    'sd.website': 'Website',
    'sd.email': 'Email liên hệ',
    'sd.description': 'Mô tả',
    'sd.product': 'Danh sách sản phẩm',

    //translate language
    'tl.title':'Từ điển âm thanh',
    'tl.content':'Nội dung',
    'tl.languagenotfound':'Chưa chọn ngôn ngữ',
    'tl.result':'Kết quả',
    'tl.chooselang':'Chọn ngôn ngữ',
    'tl.cancel':'Thoát',

    //shopping
    'shp.title': 'Địa điểm mua sắm',
    'shp.type': 'Loại cửa hàng',
    'shp.all': 'Tất cả',
    'shp.noresult': 'Không có dữ liệu',

    //sight-seeing
    'ss.back': 'Back',
    'ss.addtoplan': 'Thêm vào lịch trình',
    'ss.note': 'Ghi chú',
    'ss.call': 'Gọi',
    'ss.rate': 'Đánh giá',
    'ss.takephoto': 'Đóng góp',
    'ss.route': 'Chỉ đường',
    'ss.introduction': 'GIỚI THIỆU',
    'ss.address': 'Địa chỉ',
    'ss.operationtime': 'Khung giờ hoạt động',
    'ss.phoneno': 'Số điện thoại',
    'ss.website': 'Website',
    'ss.email': 'Email liên hệ',
    'ss.description': 'Mô tả',

    //tour guide
    'tgs.title': 'Tra cứu và xác thực thông tin hướng dẫn viên',
    'tgs.searchByText': 'Tra cứu',
    'tgs.searchByScan': 'Quét thẻ',
    'tgs.searchWithName': 'Họ tên HDV',
    'tgs.searchWithCardCode': 'Mã HDV',
    'tgs.name': 'Họ tên',
    'tgs.cardcode': 'Số thẻ',
    'tgs.status': 'Trạng thái',
    'tgs.expired_date': 'Ngày hết hạn',
    'tgs.license_src': 'Nơi cấp',
    'tgs.langs': 'Ngoại ngữ',
    'tgs.experience': 'Kinh nghiệm',
    'tgs.type': 'Loại thẻ',
    'tgs.errorScan': 'Không tìm thấy kết quả phù hợp',

    //user
    'user.title': 'Tài khoản',
    'user.hobby': 'Sở thích',
    'user.hobbydescrition': 'Chọn sở thích phù hợp với bạn',
    'user.planhistory': 'Lịch sử lịch trình',
    'user.planhistorydescription': 'Xem lại những booking đã tạo',
    'user.bookinghistory': 'Lịch sử booking',
    'user.bookinghistorydescription': 'Xem lại những lịch trình đã tạo',
    'user.mysaved': 'Địa điểm đã lưu',
    'user.mysaveddescription': 'Danh sách các địa điểm đã lưu',
    'user.mynote': 'Ghi chú',
    'user.mynotedescription': 'Xem lại những địa điểm bạn đã ghi chú',

    //userbooking
    'userbooking.title': 'Lịch sử booking',
    'userbooking.fromdate': 'Từ ngày',
    'userbooking.dayu': 'Ngày',
    'userbooking.todate': 'đến ngày',
    'userbooking.at': 'lúc',

    //user change info
    'uci.title': 'Thay đổi thông tin cá nhân',
    'uci.changeinfo': 'Thay đổi thông tin',
    'uci.fname': 'Họ',
    'uci.lname': 'Tên',
    'uci.address': 'Địa chỉ',
    'uci.phoneno': 'Số điện thoại',
    'uci.modify': 'Cập nhập thông tin',
    'uci.changepwd': 'Thay đổi mật khẩu',
    'uci.oldpwd': 'Mật khẩu cũ',
    'uci.newpwd': 'Mật khẩu mới',
    'uci.confirmnewpwd': 'Xác nhận mật khẩu mới',
    'uci.btnchangepwd': 'Đổi mật khẩu',
    'uci.tabtitle': 'Chọn thông tin cần thay đổi',
    'uci.errorfieldrequired': "Trường \"Tên\" và \"Họ\" bắt buộc không được bỏ trống",
    'uci.successupdateduser': "Cập nhập thông tin tài khoản thành công",
    'uci.wrongOldPassword': "Nhập sai password cũ",
    'uci.wrongConfirmPassword': "Xác nhận mật khẩu không đúng",
    'uci.failupdateduser': "Có sự cố xảy ra khi cập nhật. Vui lòng thử lại sau.",
    'uci.duppicationphone': 'Số điện thoại này đã được sử dụng để đăng kí. Vui lòng sử dụng số điện thoại khác.',

    //user complaint
    'ucp.title': 'Phản ánh',
    'ucp.subtitle': 'Tiêu đề',
    'ucp.placetoreport': 'Đối tượng phản ánh',
    'ucp.content': 'Nội dung',
    'ucp.post': 'Đăng',
    'ucp.clue': 'Chức nằng này dùng để tố cáo, phản ánh và góp ý đến cơ quan chức năng về chất lượng, dịch vụ du lịch của '+Parameter.cityName_VN,
    'ucp.telephone': 'Điện thoại',
    'ucp.required': 'Trường bắt buộc',
    'ucp.optional': 'Tùy chọn',
    'ucp.fullname': 'Tên',
    'ucp.requiredField': 'Vui lòng chọn ít nhất một mục phản ánh.',
    'ucp.sendSuccess': 'Chúng tôi đã nhận được thông tin phản ánh/ góp ý của bạn, thông tin sẽ được chuyển đến các cơ quan chức năng để xử lý. Xin chân thành cảm ơn!',
    'ucp.warning': 'Vui lòng điền đầy đủ thông tin vào các mục bắt buộc.',

    //user feedback detail
    'ufd.title': 'Báo cáo sai phạm',
    'ufd.content': 'Nội dung',
    'ufd.post': 'Đăng',

    //user hobby
    'ub.title': 'Sở thích du lịch',

    //user images
    'ui.title': 'Hình ảnh của',

    //user note
    'un.title': 'Ghi chú',
    'un.description': 'Ghi chú của bạn',

    //user rate
    'ur.title': 'Đánh giá',
    'ur.content': 'Nội dung',
    'ur.point': 'Điểm',
    
    //user wishlist - mysaved
    'mysaved.title': 'Các địa điểm đã lưu',
    'mysaved.mustsee': 'Gợi ý',
    'mysaved.mysaved': 'Yêu thích',
    'mysaved.direction': 'Chỉ đường',
    'mysaved.remove': 'Hủy',
    'mysaved.address': 'Địa chỉ',

    //ultility location list
    'ull.title': 'Địa điểm tiện ích',
    'ull.route': 'Chỉ đường',

    //utilities type list
    'utl.title': 'Tiện ích du lịch',
    'utl.weather': 'Thời tiết',
    'utl.translate': 'Từ điển âm thanh', 
    'utl.tourguide': 'Hướng dẫn viên',

    //weather
    'weather.title': 'Tiện ích thời tiết',
    'weather.followingdays': 'Dự báo các ngày tiếp theo',
    'weather.high': 'Cao',
    'weather.low': 'Thấp',

    //tour-ar
    'tar.title': 'Tham quan bằng chế độ Camera',
    'tar.loading': 'Đang load dữ liệu và đồng bộ',

    //list-note
    'note-list.title': 'Ghi chú',
    'note-list.viewnote': 'Xem ghi chú',

    'error.valid.required': 'Không được để trống',
    'error.valid.minLength': 'Nhập ít nhất {{0}} kí tự',
    'error.valid.maxLength': 'Nhập tối đa {{0}} kí tự',
    'error.valid.minValue': 'Giá trị không ít hơn {{0}}',
    'error.valid.maxValue': 'Giá trị không vượt quá {{0}}',
    'error.valid.dateFormat': '',
    'form.button.submit': 'Lưu',
    'form.button.reset': 'Nhập lại',
    'form.button.close': 'Thoát',
    'action.success': 'Thành công',
    'action.error': 'Thất bại',

    //trang quickbooking - error popup
    'map.cancelButton': 'Đóng',
    'quickBooking.noResult': 'Không tìm thấy khách sạn nào thích hợp. Vui lòng chọn vị trí khác!',
    'quickBooking.noResultNext': 'Không tìm thấy khách sạn nào thích hợp. Bạn có muốn mở rộng phạm vi tìm kiếm ko?',

    //locales.properties
    'network.error': 'Mất kết nối đến máy chủ.',
    'network.title': 'Lỗi',
    'info.title': 'Thông báo',
    'info.baotri': 'Chức năng đang bảo trì và sẽ trở lại sau.',
    'info.gps': 'Đã có sự thay đổi về tọa độ. Vui lòng chờ hệ thống kiểm tra địa điểm xung quanh bạn.',
    'info.deviceonly': 'GPS của thiết bị đang hoạt động rất chậm và không có phản hồi. Vui lòng sử dụng chế độ "High Acuracy".(Chế độ Sử dụng GPS, Wi-Fi và các mạng di động)',
    'warning.title': 'Cảnh báo',
    'error.title': 'Cảnh báo lỗi',
    'gps.error': 'Hiện không bật GPS hoặc ứng dụng đã bị chặn không được cho phép sử dụng GPS của thiết bị. Vui lòng bật GPS của hệ thống, hoặc cho phép ứng dụng sử dụng GPS của hệ thống.',
    'gps.error1': 'Ứng dụng không được quyền truy cập GPS của hệ thống. Vui lòng cho phép ứng dụng sử dụng GPS trong phần cài đặt.',
    'mysaved.tick': 'Thêm yêu thích',
    'mysaved.untick': 'Bỏ yêu thích',

    //Joint part
    'info.from': 'Từ',
    'info.to': 'đến',

    "errors.UserName.duplicate": "Tên tài khoản không khả dụng. Xin vui lòng sử dụng tên khác.",
    'error.invaliddatefrom': 'Chọn ngày không được trước ngày hiện tại',
    'error.invalidmaximum': 'Lịch trình không được vượt quá 4 ngày',
    'error.invalidmax7': "Lịch trình không vượt quá 7 ngày",
    'error.invalidmin1': "Lịch trình phải có ít nhất 1 ngày",
    'error.invalidoperation': 'Thời gian thiết lập trước giờ mở cửa, xin vui lòng chọn lại',
    'error.invalidclosetime': 'Thời gian thiết lập sau giờ đóng cửa, xin vui lòng chọn lại',
    'error.invalidtime': 'Thời gian được thiết lập không khả dụng. Vui lòng thiết lập lại thời gian khác',
    'error.suggesttime': 'Thời gian được thiết lập không khả dụng. Thời gian khả dụng là: ',
    'error.invalidsame': "Điểm bắt đầu và kết thúc phải khác nhau",
    'error.invalidfromto': 'Chọn ngày đi phải hơn ngày hiện tại ít nhất 1 ngày',
    'error.differfromto': 'Ngày checkin và checkout không được quá 4 ngày',
    'error.invalidmail': "Email không đúng định dạng",
    'error.requestmorethanav': "Số lượng phòng yêu cầu vượt quá số phòng còn lại",
    'token.usernameHaveSpecialString': 'Tên đăng nhập KHÔNG ĐỦ 6 kí tự hoặc chứa kí tự HOA hoặc kí tự ĐẶC BIỆT KHÁC. Vui lòng xem lại',
	'error.invalidnumber': 'Không đúng định dạng số',
    'error.quantityzero': 'Số lượng phải lớn hơn 0',

    'warning.changetime': 'Thêm địa điểm vào đã làm thay đổi thời gian, vui lòng xem lại lịch trình',
    'warning.deleteplan': "Bạn có muốn xóa ngày này trong lịch trình?",
    'warning.savechange': "Đã có sự thay đổi trong lịch trình, bạn có muốn lưu lại sự thay đổi này?",
    'warning.suggestlogin': 'Vui lòng đăng nhập để sử dụng các lịch trình được đề xuất',
    'warning.changeplanname': 'Đổi tên lịch trình',
    'warning.inputname': "Nhập vào tên mới cho lịch trình",
    'warning.checkAV': "Vui lòng kiểm tra phòng trống của loại cần yêu cầu",
    'warning.outoforder': "Phòng cần đặt hiện đã hết",
    'warning.fillform': "Xin vui lòng nhập đầy đủ thông tin",
    'warning.timenotexpire': "Thời gian chờ từ lần quick booking cuối là 1 phút. Xin vui lòng chờ.",

    'info.swapping': 'Chọn 2 địa điểm để đổi chỗ với nhau',
    'info.saved': "Thay đổi đã được lưu lại",
    'info.successfulcreate': "Tạo tour thành công. Hãy vào lịch sử để tiếp tục thay đổi",
    'info.successfulcreatesuggest': 'Lịch trình đã được đề xuất. Bạn có lưu lại hay không?',
    'info.succesfullymodify': "Lịch trình đã được lưu vào lịch sử. Xin ghé đến lịch sử lịch trình để xem hoặc chỉnh sửa",
    'info.requestcreate': "Bạn vừa tạo một lịch trình mới, bạn có muốn lưu lại không",
    'info.successbkr': "Đặt phòng thành công. Yêu cầu đã được gửi đi",
    'info.successbkt': "Đặt bàn thành công. Yêu cầu đã được gửi đi",
    'info.emotion': 'Cảm xúc hiện tại của được phân tích như sau ',
    'info.successfulregister': "Bạn đã tạo tài khoản thành công. Hãy đăng nhập để sử dụng nhiều tính năng khác.",

    //register
    'register.logForm.Address': 'Địa chỉ',
    'register.logForm.Phone': 'Điện thoại',
    'register.logForm.ConfirmPassword': 'Xác nhận mật khẩu',

    //Emotion
    "anger": "Phẫn nộ",
    "fear": "Sợ hãi",
    "happiness": "Hạnh phúc",
    "neutral": "Bình thường",
    "sadness": "Buồn",
    "surprise": "Ngạc nhiên",

    // Time translate
    'data.night': 'đêm',
    'data.hour': 'giờ',
    'data.hours': 'giờ',
    'data.day': 'ngày',
    'data.days': 'ngày',
    'data.minutes': 'phút',
    'data.minute': 'phút',
    'data.years': 'năm',
    'data.month': 'tháng',
    'data.months': 'tháng',
    
    'recognitioning': 'Đang ghi âm',
    'recognitioning.stop': 'Dừng',

    'slideshow.title': 'Những hình ảnh về địa điểm',
    'lctlk.dishes': 'Món',
    'lctlk.session': 'Buổi',
    'overview.entertainment': 'Giải trí',
    'overview.nightlife': 'Về đêm',
    'lctlk.entertainment':'Giải trí',

    "newweather.title": "Dự báo thời tiết " + Parameter.cityName_VN,

    'w200': 'Mưa nhỏ và có giông vài nơi',
    'w201': 'Mưa và giông vài nơi',
    'w202': 'Mưa lớn và giông',
    'w210': 'Mưa giông',
    'w211': 'Mưa giông rải rác',
    'w212': 'Mưa giông',
    'w221': 'Mưa lớn, có giông và sấm sét',
    'w230': 'Mưa rào rải rác và có giông vài nơi',
    'w231': 'Mưa rào và có giông',
    'w232': 'Mưa lớn, có giông và sấm sét',
    'w300': 'Mưa phùn nhẹ',
    'w301': 'Mưa phùn',
    'w302': 'Mưa phùn nặng hạt',
    'w310': 'Mưa phùn nhẹ',
    'w311': 'Mưa phùn',
    'w312': 'Mưa phùn nặng hạt',
    'w313': 'Mưa phùn ',
    'w314': 'Mưa phùn nặng hạt',
    'w321': 'Mưa phùn',
    'w500': 'Ít mây và có khả năng mưa',
    'w501': 'Nhiều mây và có khả năng mưa',
    'w502': 'Nhiều mây và có khả năng mưa to đến rất to',
    'w503': 'Mưa lớn',
    'w504': 'Mưa nặng hạt',
    'w511': 'Mưa đá',
    'w520': 'Mưa nhỏ',
    'w521': 'Mưa vừa và nhỏ',
    'w522': 'Mưa lớn',
    'w531': 'Mưa nặng hạt',
    'w600': 'Tuyết rơi',
    'w601': 'Tuyết rơi',
    'w602': 'Tuyết rơi nặng',
    'w611': 'Mưa tuyết',
    'w612': 'Mưa tuyết',
    'w615': 'Mưa tuyết',
    'w616': 'Mưa tuyết',
    'w620': 'Mưa tuyết',
    'w621': 'Mưa tuyết',
    'w622': 'Mưa tuyết',
    'w701': 'Sương mù',
    'w711': 'Sương khói',
    'w721': 'Sương mù',
    'w731': 'Cát, bụi',
    'w741': 'Sương mù',
    'w751': 'Cát',
    'w761': 'Bụi',
    'w762': 'Tro núi lửa',
    'w771': 'Sấm sét',
    'w781': 'Bão',
    'w800': 'Quang mây',
    'w801': 'Ít mây',
    'w802': 'Mây rải rác',
    'w803': 'Nhiều mây',
    'w804': 'Mây âm u',

    'cal.mon': 'Thứ hai',
    'cal.tue': 'Thứ ba',
    'cal.wed': 'Thứ tư',
    'cal.thu': 'Thứ năm',
    'cal.fri': 'Thứ sáu',
    'cal.sat': 'Thứ bảy',
    'cal.sun': 'Chủ nhật',

    'forecast.n3': 'Dự báo trong 3 giờ tiếp theo'
};